-- =========================================================================
-- Supabase PostgreSQL Schema for SolarTrack Purchase Shipment System
-- =========================================================================

CREATE TABLE IF NOT EXISTS settings (
  "Key" TEXT PRIMARY KEY,
  "Value" TEXT
);

CREATE TABLE IF NOT EXISTS vendors (
  "VendorName" TEXT PRIMARY KEY,
  "Address" TEXT,
  "Phone" TEXT,
  "GSTIN" TEXT,
  "Email" TEXT,
  "Remarks" TEXT
);

CREATE TABLE IF NOT EXISTS items (
  "ItemName" TEXT PRIMARY KEY,
  "Category" TEXT,
  "Unit" TEXT,
  "HSNCode" TEXT,
  "GSTPercent" TEXT,
  "Status" TEXT
);

CREATE TABLE IF NOT EXISTS installments (
  "SlNo" BIGINT PRIMARY KEY,
  "Name" TEXT,
  "Status" TEXT,
  "District" TEXT,
  "Address" TEXT,
  "MobileNumber" TEXT,
  "CommittedBrand" TEXT,
  "FirstInstallment" NUMERIC,
  "SecondInstallment" NUMERIC,
  "ThirdInstallment" NUMERIC,
  "Total" NUMERIC,
  "CommittedPrice" NUMERIC,
  "VendorPrice" NUMERIC,
  "VendorPaid" NUMERIC,
  "LoginDate" TEXT,
  "InstallationDate" TEXT,
  "Commission" NUMERIC,
  "CommissionPaid" NUMERIC,
  "BrokerName" TEXT,
  "BrokerNumber" TEXT,
  "CommissioningDate" TEXT
);

CREATE TABLE IF NOT EXISTS installment_txns (
  "TxnID" TEXT PRIMARY KEY,
  "SlNo" BIGINT,
  "TxnDate" TEXT,
  "Amount" NUMERIC,
  "Remark" TEXT,
  "TxnType" TEXT DEFAULT 'Customer'
);

CREATE TABLE IF NOT EXISTS commission_txns (
  "TxnID" TEXT PRIMARY KEY,
  "SlNo" BIGINT,
  "TxnDate" TEXT,
  "Amount" NUMERIC,
  "Remark" TEXT
);

CREATE TABLE IF NOT EXISTS installment_remarks (
  "RemarkID" TEXT PRIMARY KEY,
  "SlNo" BIGINT,
  "Type" TEXT,
  "Remark" TEXT,
  "CreatedAt" TEXT
);

CREATE TABLE IF NOT EXISTS shipment_remarks (
  "RemarkID" TEXT PRIMARY KEY,
  "ShipmentNo" TEXT,
  "Remark" TEXT,
  "CreatedAt" TEXT
);

CREATE TABLE IF NOT EXISTS products (
  "ProductName" TEXT PRIMARY KEY,
  "CreatedAt" TEXT
);

CREATE TABLE IF NOT EXISTS product_items (
  "RowID" TEXT PRIMARY KEY,
  "ProductName" TEXT,
  "ItemName" TEXT,
  "Price" NUMERIC
);

CREATE TABLE IF NOT EXISTS shipments (
  "ShipmentNo" TEXT PRIMARY KEY,
  "PurchaseDate" TEXT,
  "VendorName" TEXT,
  "ShipmentType" TEXT,
  "VehicleNumber" TEXT,
  "InvoiceNumber" TEXT,
  "TransportationCost" NUMERIC,
  "GSTPercentage" NUMERIC,
  "VendorPaid" NUMERIC,
  "TransportPaid" NUMERIC,
  "Documents" TEXT,
  "Remarks" TEXT,
  "CreatedAt" TEXT
);

CREATE TABLE IF NOT EXISTS materials (
  "RowID" TEXT PRIMARY KEY,
  "ShipmentNo" TEXT,
  "ItemName" TEXT,
  "Category" TEXT,
  "Quantity" NUMERIC,
  "Unit" TEXT,
  "PurchaseRate" NUMERIC,
  "TotalPurchaseValue" NUMERIC
);

CREATE TABLE IF NOT EXISTS borrowers (
  "BorrowerID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Name" TEXT NOT NULL,
  "Mobile" TEXT,
  "Address" TEXT,
  "Status" TEXT DEFAULT 'Active',
  "CreatedAt" TEXT,
  "CreatedBy" TEXT
);

CREATE TABLE IF NOT EXISTS borrower_txns (
  "TxnID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "BorrowerID" BIGINT NOT NULL,
  "TxnDate" TEXT NOT NULL,
  "Amount" NUMERIC NOT NULL,
  "Type" TEXT NOT NULL,
  "Remarks" TEXT,
  "CreatedAt" TEXT
);

-- =========================================================================
-- Performance Optimization Indexes
-- =========================================================================
CREATE INDEX IF NOT EXISTS idx_borrower_txns_borrowerid ON borrower_txns("BorrowerID");
CREATE INDEX IF NOT EXISTS idx_borrower_txns_txndate ON borrower_txns("TxnDate");
CREATE INDEX IF NOT EXISTS idx_materials_shipmentno ON materials("ShipmentNo");
CREATE INDEX IF NOT EXISTS idx_installment_txns_slno ON installment_txns("SlNo");
CREATE INDEX IF NOT EXISTS idx_commission_txns_slno ON commission_txns("SlNo");
CREATE INDEX IF NOT EXISTS idx_installment_remarks_slno ON installment_remarks("SlNo");
CREATE INDEX IF NOT EXISTS idx_shipment_remarks_shipmentno ON shipment_remarks("ShipmentNo");
CREATE INDEX IF NOT EXISTS idx_product_items_productname ON product_items("ProductName");
CREATE INDEX IF NOT EXISTS idx_shipments_purchasedate ON shipments("PurchaseDate");
CREATE INDEX IF NOT EXISTS idx_installments_status ON installments("Status");


-- =========================================================================
-- Authentication & Authorization Schema (Added for DB-backed Auth)
-- =========================================================================
CREATE TABLE IF NOT EXISTS roles (
  "role" TEXT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS users (
  "userid" TEXT PRIMARY KEY,
  "username" TEXT,
  "email" TEXT UNIQUE,
  "password" TEXT,
  "role" TEXT REFERENCES roles("role"),
  "status" TEXT,
  "reset_token" TEXT,
  "reset_expires" TEXT,
  "created_at" TEXT
);

CREATE TABLE IF NOT EXISTS notifications (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" TEXT,
  "user_id" TEXT,
  "message" TEXT,
  "status" TEXT DEFAULT 'unread',
  "created_at" TEXT
);

-- Pre-populate default roles
INSERT INTO roles ("role") VALUES 
  ('admin'), 
  ('superadmin'), 
  ('partner'), 
  ('user')
ON CONFLICT DO NOTHING;

-- Pre-populate default admin user
INSERT INTO users ("userid", "username", "email", "password", "role", "status", "created_at") VALUES 
  ('admin', 'Admin', 'admin@example.com', 'adminpassword', 'admin', 'Approved', '2026-07-23T10:46:05+05:30')
ON CONFLICT DO NOTHING;


