/* =========================================================================
   sizing-db.js — Inverter & Battery Master Database & Calculation Parameters
   Stores active product catalogues (GTI, PCU, Hybrid, UPS & Lead-Acid/Lithium batteries)
   and configurable sizing parameters.
   ========================================================================= */

const SizingDB = (() => {

  const DEFAULT_PARAMS = {
    safetyMarginPct: 25,         // 20-30% default safety margin
    inverterEfficiencyPct: 90,   // 90% default DC-AC conversion efficiency
    lithiumDoDPct: 90,           // 90% DoD for Lithium LFP
    tubularDoDPct: 75,           // 75-80% DoD for Tall Tubular
    flatPlateDoDPct: 65,         // 65-70% DoD for Flat Plate
    leadAcidDoDPct: 75,          // Harmonized generic lead-acid DoD (defaults to Tubular)
    batteryChargingEffPct: 88,   // 88% battery charging efficiency
    peakSunHours: 5.0,           // 5.0 kWh/m2/day actual solar irradiation
    inverterLossPct: 4,          // 4% Inverter conversion & MPPT loss
    dcAcCableLossPct: 2,         // 2% DC/AC cable ohmic loss
    tempLossPct: 7,              // 7% Temperature thermal derating loss
    soilingLossPct: 4,           // 4% Dust & soiling loss
    shadingOrientationLossPct: 3,// 3% Orientation, tilt & near-shading loss
    pvSystemEfficiencyPct: 78,   // 78% overall compound PR yield efficiency
    acNonInverterSurgeFactor: 3.0,
    acInverterSurgeFactor: 1.5,
    pumpSurgeFactor: 3.5,
    preferredBatteryType: 'lithium', // 'lithium', 'tubular', or 'flat-plate'
    selectedDiscom: 'odisha_oerc',
    energyCalculationBasis: 'backup_duration' // 'backup_duration' or 'appliance_schedule'
  };

  const TARIFF_SCHEDULES = {
    'odisha_oerc': {
      id: 'odisha_oerc',
      state: 'Odisha',
      name: 'Odisha OERC (TPCODL / TPNODL / TPSODL / TPWODL)',
      category: 'Residential Domestic (LT-Domestic)',
      slabs: [
        { name: '1 to 50 Units', min: 0, max: 50, rate: 2.90 },
        { name: '51 to 200 Units', min: 50, max: 200, rate: 4.70 },
        { name: '201 to 400 Units', min: 200, max: 400, rate: 5.70 },
        { name: 'Above 400 Units', min: 400, max: Infinity, rate: 6.10 }
      ],
      fixedChargePerKw: 20,
      meterRent: 10,
      electricityDutyPct: 4,
      singlePhaseMaxKw: 5.0,
      netMeteringAllowed: true
    },
    'national_standard': {
      id: 'national_standard',
      state: 'National Benchmark',
      name: 'National Standard Average Residential',
      category: 'Residential Domestic',
      slabs: [
        { name: '1 to 100 Units', min: 0, max: 100, rate: 4.50 },
        { name: '101 to 300 Units', min: 100, max: 300, rate: 6.20 },
        { name: '301 to 500 Units', min: 300, max: 500, rate: 7.50 },
        { name: 'Above 500 Units', min: 500, max: Infinity, rate: 8.50 }
      ],
      fixedChargePerKw: 50,
      meterRent: 15,
      electricityDutyPct: 5,
      singlePhaseMaxKw: 5.0,
      netMeteringAllowed: true
    },
    'commercial_standard': {
      id: 'commercial_standard',
      state: 'All India',
      name: 'Commercial & Non-Domestic General',
      category: 'Commercial (LT-General)',
      slabs: [
        { name: 'All Units (Flat Commercial Tariff)', min: 0, max: Infinity, rate: 8.50 }
      ],
      fixedChargePerKw: 150,
      meterRent: 25,
      electricityDutyPct: 6,
      singlePhaseMaxKw: 5.0,
      netMeteringAllowed: true
    }
  };

  const DEFAULT_INVERTERS = [
    // ---------------- Home UPS / Sine Wave Inverters (Without Solar) ----------------
    {
      id: 'inv-1',
      brand: 'Microtek',
      model: 'UPS SEBz 1100',
      type: 'UPS',
      kVA: 0.9,
      kW: 0.72,
      phase: '1-Phase',
      batteryVoltage: 12,
      continuousOutput: 720,
      surgeOutput: 1440,
      surgeDuration: 5,
      maxPvInput: 0,
      mpptVoltageRange: 'N/A',
      maxPvCurrent: 0,
      maxChargingCurrent: 15,
      maxBatteryDischargeCurrent: 75,
      ipRating: 'IP20 (Indoor)',
      warranty: 2,
      active: true
    },
    {
      id: 'inv-2',
      brand: 'Luminous',
      model: 'Zelio+ 1700',
      type: 'UPS',
      kVA: 1.5,
      kW: 1.2,
      phase: '1-Phase',
      batteryVoltage: 24,
      continuousOutput: 1200,
      surgeOutput: 2400,
      surgeDuration: 5,
      maxPvInput: 0,
      mpptVoltageRange: 'N/A',
      maxPvCurrent: 0,
      maxChargingCurrent: 15,
      maxBatteryDischargeCurrent: 60,
      ipRating: 'IP20 (Indoor)',
      warranty: 2,
      active: true
    },
    {
      id: 'inv-2b',
      brand: 'Luminous',
      model: 'Cruze 2.5kVA / 36V',
      type: 'UPS',
      kVA: 2.5,
      kW: 2.0,
      phase: '1-Phase',
      batteryVoltage: 36,
      continuousOutput: 2000,
      surgeOutput: 4000,
      surgeDuration: 5,
      maxPvInput: 0,
      mpptVoltageRange: 'N/A',
      maxPvCurrent: 0,
      maxChargingCurrent: 20,
      maxBatteryDischargeCurrent: 65,
      ipRating: 'IP20 (Indoor)',
      warranty: 2,
      active: true
    },
    {
      id: 'inv-3',
      brand: 'Microtek',
      model: 'Super Power 3.5kVA',
      type: 'UPS',
      kVA: 3.5,
      kW: 2.8,
      phase: '1-Phase',
      batteryVoltage: 48,
      continuousOutput: 2800,
      surgeOutput: 5600,
      surgeDuration: 5,
      maxPvInput: 0,
      mpptVoltageRange: 'N/A',
      maxPvCurrent: 0,
      maxChargingCurrent: 20,
      maxBatteryDischargeCurrent: 70,
      ipRating: 'IP20 (Indoor)',
      warranty: 2,
      active: true
    },
    {
      id: 'inv-3b',
      brand: 'Luminous',
      model: 'Cruze+ 5kVA / 48V',
      type: 'UPS',
      kVA: 5.0,
      kW: 4.0,
      phase: '1-Phase',
      batteryVoltage: 48,
      continuousOutput: 4000,
      surgeOutput: 8000,
      surgeDuration: 5,
      maxPvInput: 0,
      mpptVoltageRange: 'N/A',
      maxPvCurrent: 0,
      maxChargingCurrent: 25,
      maxBatteryDischargeCurrent: 95,
      ipRating: 'IP20 (Indoor)',
      warranty: 2,
      active: true
    },
    {
      id: 'inv-3c',
      brand: 'Microtek',
      model: 'Heavy Duty 7.5kVA / 96V',
      type: 'UPS',
      kVA: 7.5,
      kW: 6.0,
      phase: '1-Phase',
      batteryVoltage: 96,
      continuousOutput: 6000,
      surgeOutput: 12000,
      surgeDuration: 5,
      maxPvInput: 0,
      mpptVoltageRange: 'N/A',
      maxPvCurrent: 0,
      maxChargingCurrent: 30,
      maxBatteryDischargeCurrent: 75,
      ipRating: 'IP20 (Indoor)',
      warranty: 2,
      active: true
    },
    {
      id: 'inv-3d',
      brand: 'Luminous',
      model: 'Pro Heavy 10kVA / 120V',
      type: 'UPS',
      kVA: 10.0,
      kW: 8.0,
      phase: '1-Phase',
      batteryVoltage: 120,
      continuousOutput: 8000,
      surgeOutput: 16000,
      surgeDuration: 5,
      maxPvInput: 0,
      mpptVoltageRange: 'N/A',
      maxPvCurrent: 0,
      maxChargingCurrent: 35,
      maxBatteryDischargeCurrent: 80,
      ipRating: 'IP20 (Indoor)',
      warranty: 2,
      active: true
    },

    // ---------------- Solar PCU (Off-Grid Solar) ----------------
    {
      id: 'inv-4a',
      brand: 'Luminous Solar',
      model: 'Solar PCU 1kVA / 12V',
      type: 'PCU',
      kVA: 1.0,
      kW: 0.8,
      phase: '1-Phase',
      batteryVoltage: 12,
      continuousOutput: 800,
      surgeOutput: 1600,
      surgeDuration: 10,
      maxPvInput: 1000,
      mpptVoltageRange: '17V - 50V',
      maxPvCurrent: 40,
      maxChargingCurrent: 20,
      maxBatteryDischargeCurrent: 75,
      ipRating: 'IP21',
      warranty: 2,
      active: true
    },
    {
      id: 'inv-4',
      brand: 'Luminous Solar',
      model: 'Solar PCU 2kVA / 24V',
      type: 'PCU',
      kVA: 2.0,
      kW: 1.6,
      phase: '1-Phase',
      batteryVoltage: 24,
      continuousOutput: 1600,
      surgeOutput: 3200,
      surgeDuration: 10,
      maxPvInput: 2000,
      mpptVoltageRange: '30V - 90V',
      maxPvCurrent: 50,
      maxChargingCurrent: 30,
      maxBatteryDischargeCurrent: 80,
      ipRating: 'IP21',
      warranty: 2,
      active: true
    },
    {
      id: 'inv-4b',
      brand: 'Eastman Solar',
      model: 'Solar PCU 3kVA / 36V',
      type: 'PCU',
      kVA: 3.0,
      kW: 2.4,
      phase: '1-Phase',
      batteryVoltage: 36,
      continuousOutput: 2400,
      surgeOutput: 4800,
      surgeDuration: 10,
      maxPvInput: 3000,
      mpptVoltageRange: '45V - 120V',
      maxPvCurrent: 55,
      maxChargingCurrent: 35,
      maxBatteryDischargeCurrent: 75,
      ipRating: 'IP21',
      warranty: 2,
      active: true
    },
    {
      id: 'inv-5',
      brand: 'Havells Solar',
      model: 'Solar PCU 3.75kVA / 48V',
      type: 'PCU',
      kVA: 3.75,
      kW: 3.0,
      phase: '1-Phase',
      batteryVoltage: 48,
      continuousOutput: 3000,
      surgeOutput: 6000,
      surgeDuration: 10,
      maxPvInput: 3750,
      mpptVoltageRange: '60V - 140V',
      maxPvCurrent: 60,
      maxChargingCurrent: 40,
      maxBatteryDischargeCurrent: 75,
      ipRating: 'IP21',
      warranty: 2,
      active: true
    },
    {
      id: 'inv-6',
      brand: 'Luminous Solar',
      model: 'PCU NXT 5kVA / 48V',
      type: 'PCU',
      kVA: 5.0,
      kW: 4.0,
      phase: '1-Phase',
      batteryVoltage: 48,
      continuousOutput: 4000,
      surgeOutput: 8000,
      surgeDuration: 10,
      maxPvInput: 5000,
      mpptVoltageRange: '80V - 160V',
      maxPvCurrent: 80,
      maxChargingCurrent: 50,
      maxBatteryDischargeCurrent: 100,
      ipRating: 'IP21',
      warranty: 2,
      active: true
    },
    {
      id: 'inv-6b',
      brand: 'Microtek Solar',
      model: 'Solar PCU 6kVA / 48V',
      type: 'PCU',
      kVA: 6.0,
      kW: 4.8,
      phase: '1-Phase',
      batteryVoltage: 48,
      continuousOutput: 4800,
      surgeOutput: 9600,
      surgeDuration: 10,
      maxPvInput: 6000,
      mpptVoltageRange: '90V - 180V',
      maxPvCurrent: 80,
      maxChargingCurrent: 55,
      maxBatteryDischargeCurrent: 110,
      ipRating: 'IP21',
      warranty: 2,
      active: true
    },
    {
      id: 'inv-7',
      brand: 'Eastman Solar',
      model: 'Solar PCU 7.5kVA / 96V',
      type: 'PCU',
      kVA: 7.5,
      kW: 6.0,
      phase: '1-Phase',
      batteryVoltage: 96,
      continuousOutput: 6000,
      surgeOutput: 12000,
      surgeDuration: 10,
      maxPvInput: 7500,
      mpptVoltageRange: '120V - 240V',
      maxPvCurrent: 80,
      maxChargingCurrent: 60,
      maxBatteryDischargeCurrent: 75,
      ipRating: 'IP21',
      warranty: 2,
      active: true
    },
    {
      id: 'inv-7b',
      brand: 'Luminous Solar',
      model: 'PCU NXT 10kVA / 120V',
      type: 'PCU',
      kVA: 10.0,
      kW: 8.0,
      phase: '1-Phase',
      batteryVoltage: 120,
      continuousOutput: 8000,
      surgeOutput: 16000,
      surgeDuration: 10,
      maxPvInput: 10000,
      mpptVoltageRange: '150V - 300V',
      maxPvCurrent: 90,
      maxChargingCurrent: 65,
      maxBatteryDischargeCurrent: 80,
      ipRating: 'IP21',
      warranty: 2,
      active: true
    },
    {
      id: 'inv-7c',
      brand: 'Eastman Solar',
      model: 'Solar PCU 15kVA / 192V',
      type: 'PCU',
      kVA: 15.0,
      kW: 12.0,
      phase: '3-Phase',
      batteryVoltage: 192,
      continuousOutput: 12000,
      surgeOutput: 24000,
      surgeDuration: 10,
      maxPvInput: 15000,
      mpptVoltageRange: '220V - 450V',
      maxPvCurrent: 100,
      maxChargingCurrent: 70,
      maxBatteryDischargeCurrent: 75,
      ipRating: 'IP21',
      warranty: 2,
      active: true
    },

    // ---------------- Hybrid Inverters (Solar + Grid + Battery) ----------------
    {
      id: 'inv-8',
      brand: 'Growatt',
      model: 'SPH 3000 Hybrid 1-Phase',
      type: 'Hybrid',
      kVA: 3.0,
      kW: 3.0,
      phase: '1-Phase',
      batteryVoltage: 48,
      continuousOutput: 3000,
      surgeOutput: 6000,
      surgeDuration: 10,
      maxPvInput: 4500,
      mpptVoltageRange: '120V - 550V',
      maxPvCurrent: 13.5,
      maxChargingCurrent: 66,
      maxBatteryDischargeCurrent: 66,
      ipRating: 'IP65',
      warranty: 5,
      active: true
    },
    {
      id: 'inv-9',
      brand: 'Growatt',
      model: 'SPH 5000 Hybrid 1-Phase',
      type: 'Hybrid',
      kVA: 5.0,
      kW: 5.0,
      phase: '1-Phase',
      batteryVoltage: 48,
      continuousOutput: 5000,
      surgeOutput: 10000,
      surgeDuration: 10,
      maxPvInput: 7500,
      mpptVoltageRange: '120V - 550V',
      maxPvCurrent: 13.5,
      maxChargingCurrent: 100,
      maxBatteryDischargeCurrent: 100,
      ipRating: 'IP65',
      warranty: 5,
      active: true
    },
    {
      id: 'inv-9b',
      brand: 'Deye',
      model: 'SUN-6K-SG04LP1 6kW Hybrid 1-Phase',
      type: 'Hybrid',
      kVA: 6.0,
      kW: 6.0,
      phase: '1-Phase',
      batteryVoltage: 48,
      continuousOutput: 6000,
      surgeOutput: 12000,
      surgeDuration: 10,
      maxPvInput: 8000,
      mpptVoltageRange: '125V - 500V',
      maxPvCurrent: 17,
      maxChargingCurrent: 135,
      maxBatteryDischargeCurrent: 135,
      ipRating: 'IP65',
      warranty: 5,
      active: true
    },
    {
      id: 'inv-10',
      brand: 'Deye',
      model: 'SUN-8K-SG04LP1 8kW Hybrid 1-Phase',
      type: 'Hybrid',
      kVA: 8.0,
      kW: 8.0,
      phase: '1-Phase',
      batteryVoltage: 48,
      continuousOutput: 8000,
      surgeOutput: 16000,
      surgeDuration: 10,
      maxPvInput: 10400,
      mpptVoltageRange: '160V - 500V',
      maxPvCurrent: 26,
      maxChargingCurrent: 190,
      maxBatteryDischargeCurrent: 190,
      ipRating: 'IP65',
      warranty: 5,
      active: true
    },
    {
      id: 'inv-10b',
      brand: 'Growatt',
      model: 'SPH 10000TL3 Hybrid 3-Phase',
      type: 'Hybrid',
      kVA: 10.0,
      kW: 10.0,
      phase: '3-Phase',
      batteryVoltage: 48,
      continuousOutput: 10000,
      surgeOutput: 20000,
      surgeDuration: 10,
      maxPvInput: 13000,
      mpptVoltageRange: '160V - 800V',
      maxPvCurrent: 25,
      maxChargingCurrent: 200,
      maxBatteryDischargeCurrent: 200,
      ipRating: 'IP65',
      warranty: 5,
      active: true
    },
    {
      id: 'inv-11',
      brand: 'Deye',
      model: 'SUN-12K-SG04LP3 12kW Hybrid 3-Phase',
      type: 'Hybrid',
      kVA: 12.0,
      kW: 12.0,
      phase: '3-Phase',
      batteryVoltage: 48,
      continuousOutput: 12000,
      surgeOutput: 24000,
      surgeDuration: 10,
      maxPvInput: 15600,
      mpptVoltageRange: '160V - 800V',
      maxPvCurrent: 26,
      maxChargingCurrent: 240,
      maxBatteryDischargeCurrent: 240,
      ipRating: 'IP65',
      warranty: 5,
      active: true
    },
    {
      id: 'inv-11b',
      brand: 'Deye',
      model: 'SUN-15K-SG04LP3 15kW Hybrid 3-Phase',
      type: 'Hybrid',
      kVA: 15.0,
      kW: 15.0,
      phase: '3-Phase',
      batteryVoltage: 48,
      continuousOutput: 15000,
      surgeOutput: 30000,
      surgeDuration: 10,
      maxPvInput: 19500,
      mpptVoltageRange: '160V - 800V',
      maxPvCurrent: 32,
      maxChargingCurrent: 280,
      maxBatteryDischargeCurrent: 280,
      ipRating: 'IP65',
      warranty: 5,
      active: true
    },

    // ---------------- Grid-Tied Inverters (On-Grid Solar GTI) ----------------
    {
      id: 'inv-12a',
      brand: 'Solis',
      model: 'S6-GR1P1K 1kW GTI 1-Phase',
      type: 'GTI',
      kVA: 1.0,
      kW: 1.0,
      phase: '1-Phase',
      batteryVoltage: 0,
      continuousOutput: 1000,
      surgeOutput: 1100,
      surgeDuration: 5,
      maxPvInput: 1500,
      mpptVoltageRange: '50V - 450V',
      maxPvCurrent: 14,
      maxChargingCurrent: 0,
      maxBatteryDischargeCurrent: 0,
      ipRating: 'IP65',
      warranty: 5,
      active: true
    },
    {
      id: 'inv-12b',
      brand: 'Solis',
      model: 'S6-GR1P2K 2kW GTI 1-Phase',
      type: 'GTI',
      kVA: 2.0,
      kW: 2.0,
      phase: '1-Phase',
      batteryVoltage: 0,
      continuousOutput: 2000,
      surgeOutput: 2200,
      surgeDuration: 5,
      maxPvInput: 3000,
      mpptVoltageRange: '70V - 500V',
      maxPvCurrent: 14,
      maxChargingCurrent: 0,
      maxBatteryDischargeCurrent: 0,
      ipRating: 'IP65',
      warranty: 5,
      active: true
    },
    {
      id: 'inv-12',
      brand: 'Solis',
      model: 'S6-GR1P3K 3kW GTI 1-Phase',
      type: 'GTI',
      kVA: 3.0,
      kW: 3.0,
      phase: '1-Phase',
      batteryVoltage: 0,
      continuousOutput: 3000,
      surgeOutput: 3300,
      surgeDuration: 5,
      maxPvInput: 4500,
      mpptVoltageRange: '90V - 520V',
      maxPvCurrent: 14,
      maxChargingCurrent: 0,
      maxBatteryDischargeCurrent: 0,
      ipRating: 'IP65',
      warranty: 5,
      active: true
    },
    {
      id: 'inv-12c',
      brand: 'Growatt',
      model: 'MIC 4000TL-X 4kW GTI 1-Phase',
      type: 'GTI',
      kVA: 4.0,
      kW: 4.0,
      phase: '1-Phase',
      batteryVoltage: 0,
      continuousOutput: 4000,
      surgeOutput: 4400,
      surgeDuration: 5,
      maxPvInput: 6000,
      mpptVoltageRange: '80V - 550V',
      maxPvCurrent: 13,
      maxChargingCurrent: 0,
      maxBatteryDischargeCurrent: 0,
      ipRating: 'IP65',
      warranty: 5,
      active: true
    },
    {
      id: 'inv-13',
      brand: 'Growatt',
      model: 'MIC 5000TL-X 5kW GTI 1-Phase',
      type: 'GTI',
      kVA: 5.0,
      kW: 5.0,
      phase: '1-Phase',
      batteryVoltage: 0,
      continuousOutput: 5000,
      surgeOutput: 5500,
      surgeDuration: 5,
      maxPvInput: 7500,
      mpptVoltageRange: '80V - 550V',
      maxPvCurrent: 13,
      maxChargingCurrent: 0,
      maxBatteryDischargeCurrent: 0,
      ipRating: 'IP65',
      warranty: 5,
      active: true
    },
    {
      id: 'inv-13b',
      brand: 'Solis',
      model: 'S6-GR1P6K 6kW GTI 1-Phase',
      type: 'GTI',
      kVA: 6.0,
      kW: 6.0,
      phase: '1-Phase',
      batteryVoltage: 0,
      continuousOutput: 6000,
      surgeOutput: 6600,
      surgeDuration: 5,
      maxPvInput: 9000,
      mpptVoltageRange: '90V - 550V',
      maxPvCurrent: 16,
      maxChargingCurrent: 0,
      maxBatteryDischargeCurrent: 0,
      ipRating: 'IP65',
      warranty: 5,
      active: true
    },
    {
      id: 'inv-13c',
      brand: 'Growatt',
      model: 'MID 8KTL3-X 8kW GTI 3-Phase',
      type: 'GTI',
      kVA: 8.0,
      kW: 8.0,
      phase: '3-Phase',
      batteryVoltage: 0,
      continuousOutput: 8000,
      surgeOutput: 8800,
      surgeDuration: 5,
      maxPvInput: 12000,
      mpptVoltageRange: '160V - 850V',
      maxPvCurrent: 25,
      maxChargingCurrent: 0,
      maxBatteryDischargeCurrent: 0,
      ipRating: 'IP65',
      warranty: 5,
      active: true
    },
    {
      id: 'inv-14',
      brand: 'Solis',
      model: 'S5-GC10K 10kW GTI 3-Phase',
      type: 'GTI',
      kVA: 10.0,
      kW: 10.0,
      phase: '3-Phase',
      batteryVoltage: 0,
      continuousOutput: 10000,
      surgeOutput: 11000,
      surgeDuration: 5,
      maxPvInput: 15000,
      mpptVoltageRange: '160V - 850V',
      maxPvCurrent: 32,
      maxChargingCurrent: 0,
      maxBatteryDischargeCurrent: 0,
      ipRating: 'IP65',
      warranty: 5,
      active: true
    },
    {
      id: 'inv-14b',
      brand: 'Sungrow',
      model: 'SG12RT 12kW GTI 3-Phase',
      type: 'GTI',
      kVA: 12.0,
      kW: 12.0,
      phase: '3-Phase',
      batteryVoltage: 0,
      continuousOutput: 12000,
      surgeOutput: 13200,
      surgeDuration: 5,
      maxPvInput: 18000,
      mpptVoltageRange: '160V - 900V',
      maxPvCurrent: 32,
      maxChargingCurrent: 0,
      maxBatteryDischargeCurrent: 0,
      ipRating: 'IP65',
      warranty: 5,
      active: true
    },
    {
      id: 'inv-15',
      brand: 'Havells Enviro',
      model: '15kW GTI 3-Phase',
      type: 'GTI',
      kVA: 15.0,
      kW: 15.0,
      phase: '3-Phase',
      batteryVoltage: 0,
      continuousOutput: 15000,
      surgeOutput: 16500,
      surgeDuration: 5,
      maxPvInput: 22500,
      mpptVoltageRange: '200V - 950V',
      maxPvCurrent: 40,
      maxChargingCurrent: 0,
      maxBatteryDischargeCurrent: 0,
      ipRating: 'IP65',
      warranty: 5,
      active: true
    },
    {
      id: 'inv-15b',
      brand: 'Solis',
      model: 'S5-GC20K 20kW GTI 3-Phase',
      type: 'GTI',
      kVA: 20.0,
      kW: 20.0,
      phase: '3-Phase',
      batteryVoltage: 0,
      continuousOutput: 20000,
      surgeOutput: 22000,
      surgeDuration: 5,
      maxPvInput: 30000,
      mpptVoltageRange: '200V - 1000V',
      maxPvCurrent: 45,
      maxChargingCurrent: 0,
      maxBatteryDischargeCurrent: 0,
      ipRating: 'IP65',
      warranty: 5,
      active: true
    }
  ];

  const DEFAULT_BATTERIES = [
    // ---------------- Tall Tubular Lead-Acid Batteries (12V) ----------------
    {
      id: 'bat-tub-150',
      brand: 'Exide',
      model: '6LMS150Ah Solar Tubular (12V 150Ah)',
      type: 'Tubular',
      chemistry: 'Lead Acid (Tubular)',
      voltage: 12,
      ah: 150,
      kWh: 1.8,
      capacityRating: 'C10',
      maxContinuousDischarge: 45,
      peakDischarge: 90,
      dod: 0.75,
      warranty: 5,
      active: true
    },
    {
      id: 'bat-tub-200',
      brand: 'Luminous',
      model: 'LPTT12200H Solar Tubular (12V 200Ah)',
      type: 'Tubular',
      chemistry: 'Lead Acid (Tubular)',
      voltage: 12,
      ah: 200,
      kWh: 2.4,
      capacityRating: 'C10',
      maxContinuousDischarge: 60,
      peakDischarge: 120,
      dod: 0.75,
      warranty: 5,
      active: true
    },
    {
      id: 'bat-tub-220',
      brand: 'Eastman',
      model: 'EM220Ah Solar Tubular (12V 220Ah)',
      type: 'Tubular',
      chemistry: 'Lead Acid (Tubular)',
      voltage: 12,
      ah: 220,
      kWh: 2.64,
      capacityRating: 'C10',
      maxContinuousDischarge: 65,
      peakDischarge: 130,
      dod: 0.75,
      warranty: 5,
      active: true
    },

    // ---------------- Flat Plate Lead-Acid Batteries (12V) ----------------
    {
      id: 'bat-fp-100',
      brand: 'Luminous',
      model: 'IL1050FP Flat Plate (12V 100Ah)',
      type: 'Flat Plate',
      chemistry: 'Lead Acid (Flat Plate)',
      voltage: 12,
      ah: 100,
      kWh: 1.2,
      capacityRating: 'C20',
      maxContinuousDischarge: 30,
      peakDischarge: 60,
      dod: 0.65,
      warranty: 2,
      active: true
    },
    {
      id: 'bat-fp-150',
      brand: 'Exide',
      model: 'InstaBrite IB1500 (12V 150Ah)',
      type: 'Flat Plate',
      chemistry: 'Lead Acid (Flat Plate)',
      voltage: 12,
      ah: 150,
      kWh: 1.8,
      capacityRating: 'C20',
      maxContinuousDischarge: 40,
      peakDischarge: 80,
      dod: 0.65,
      warranty: 3,
      active: true
    },
    {
      id: 'bat-fp-200',
      brand: 'Amaron',
      model: 'Current CR200FP (12V 200Ah)',
      type: 'Flat Plate',
      chemistry: 'Lead Acid (Flat Plate)',
      voltage: 12,
      ah: 200,
      kWh: 2.4,
      capacityRating: 'C20',
      maxContinuousDischarge: 50,
      peakDischarge: 100,
      dod: 0.65,
      warranty: 3,
      active: true
    },

    // ---------------- Lithium LFP Batteries (12V, 24V, 48V, 51.2V) ----------------
    {
      id: 'bat-li-12-100',
      brand: 'Tata Power / Livguard',
      model: 'LFP-12100 12.8V 100Ah Lithium Pack',
      type: 'Lithium LFP',
      chemistry: 'LiFePO4',
      voltage: 12.8,
      ah: 100,
      kWh: 1.28,
      capacityRating: '0.5C Continuous / 1.0C Peak',
      maxContinuousDischarge: 50,
      peakDischarge: 100,
      dod: 0.90,
      warranty: 5,
      active: true
    },
    {
      id: 'bat-li-12-150',
      brand: 'Luminous',
      model: 'LFP-12150 12.8V 150Ah Lithium Pack',
      type: 'Lithium LFP',
      chemistry: 'LiFePO4',
      voltage: 12.8,
      ah: 150,
      kWh: 1.92,
      capacityRating: '0.5C Continuous / 1.0C Peak',
      maxContinuousDischarge: 75,
      peakDischarge: 150,
      dod: 0.90,
      warranty: 5,
      active: true
    },
    {
      id: 'bat-li-24-100',
      brand: 'Growatt',
      model: 'LFP-24100 25.6V 100Ah Lithium Pack',
      type: 'Lithium LFP',
      chemistry: 'LiFePO4',
      voltage: 25.6,
      ah: 100,
      kWh: 2.56,
      capacityRating: '0.5C Continuous / 1.0C Peak',
      maxContinuousDischarge: 50,
      peakDischarge: 100,
      dod: 0.90,
      warranty: 5,
      active: true
    },
    {
      id: 'bat-li-48-100',
      brand: 'Tata Power',
      model: 'TPL-48100 48V 100Ah Lithium Pack',
      type: 'Lithium LFP',
      chemistry: 'LiFePO4',
      voltage: 48,
      ah: 100,
      kWh: 4.8,
      capacityRating: '0.5C Continuous / 1.0C Peak',
      maxContinuousDischarge: 50,
      peakDischarge: 100,
      dod: 0.90,
      warranty: 5,
      active: true
    },
    {
      id: 'bat-li-48-200',
      brand: 'Felicity Solar',
      model: 'LPBF48200 48V 200Ah Lithium Pack',
      type: 'Lithium LFP',
      chemistry: 'LiFePO4',
      voltage: 48,
      ah: 200,
      kWh: 9.6,
      capacityRating: '0.5C Continuous / 1.0C Peak',
      maxContinuousDischarge: 100,
      peakDischarge: 200,
      dod: 0.90,
      warranty: 5,
      active: true
    },
    {
      id: 'bat-li-51-120',
      brand: 'Deye',
      model: 'RW-M6.1 51.2V 120Ah Lithium Pack',
      type: 'Lithium LFP',
      chemistry: 'LiFePO4',
      voltage: 51.2,
      ah: 120,
      kWh: 6.14,
      capacityRating: '0.5C Continuous / 1.0C Peak',
      maxContinuousDischarge: 60,
      peakDischarge: 120,
      dod: 0.90,
      warranty: 10,
      active: true
    }
  ];

  function getParams() {
    try {
      const stored = localStorage.getItem('sizing_params');
      if (stored) return { ...DEFAULT_PARAMS, ...JSON.parse(stored) };
    } catch (e) { }
    return { ...DEFAULT_PARAMS };
  }

  function saveParams(params) {
    localStorage.setItem('sizing_params', JSON.stringify(params));
  }

  function getInverters() {
    try {
      const stored = localStorage.getItem('sizing_inverters');
      if (stored) return JSON.parse(stored);
    } catch (e) { }
    return [...DEFAULT_INVERTERS];
  }

  function saveInverters(list) {
    localStorage.setItem('sizing_inverters', JSON.stringify(list));
  }

  function getBatteries() {
    try {
      const stored = localStorage.getItem('sizing_batteries');
      if (stored) return JSON.parse(stored);
    } catch (e) { }
    return [...DEFAULT_BATTERIES];
  }

  function saveBatteries(list) {
    localStorage.setItem('sizing_batteries', JSON.stringify(list));
  }

  function getTariffSchedule(discomId) {
    const key = discomId || getParams().selectedDiscom || 'odisha_oerc';
    return TARIFF_SCHEDULES[key] || TARIFF_SCHEDULES['odisha_oerc'];
  }

  function getTariffList() {
    return Object.values(TARIFF_SCHEDULES);
  }

  function resetToDefaults() {
    localStorage.removeItem('sizing_params');
    localStorage.removeItem('sizing_inverters');
    localStorage.removeItem('sizing_batteries');
  }

  return {
    DEFAULT_PARAMS,
    DEFAULT_INVERTERS,
    DEFAULT_BATTERIES,
    TARIFF_SCHEDULES,
    getParams,
    saveParams,
    getInverters,
    saveInverters,
    getBatteries,
    saveBatteries,
    getTariffSchedule,
    getTariffList,
    resetToDefaults
  };

})();

